version: "3.3"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    restart: always
    ports:
      - 8000:8000

# DYNAMO_ENDPOINT=http://localhost:8000 dynamodb-admin
