version: "3.3"

services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1935:1935
