version: "3.3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a123456
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
