version: "3.7"

services:
  mariadb:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 7002:8080
